### ISSUE TITLE
Change of host url's for services

### ISSUE THREAD

**Issue by swxk19** [CS3219-AY2324S1/ay2324s1-course-assessment-g23#110]
As mentioned in PR #109 . Due to refactoring of the containers and services, containers are no longer hosted on `localhost`, but instead will call something like `http://api_gateway:8000` instead of `http://localhost:8000`. i.e. Call the container name instead of `localhost`. 
Frontend should only be calling 1 container, `api_gateway`.

@Lava-Iris do correct me if I'm wrong, and/or provide more details that you think may be useful for frontend team to know, if any.

**Comment by swxk19** [comment]
it seems `localhost` does still work, at least from some superficial testing on backend side.
Probably because there is still an explicit mapping of ports on the local machine to docker container, so docker is able to convert it, im guessing.

**Comment by EvitanRelta** [comment]
@swxk19 alright
so does frontend needa change anything for this yet?
