### ISSUE TITLE
Missing type hints

### ISSUE THREAD

**Issue by EvitanRelta** [CS3219-AY2324S1/ay2324s1-course-assessment-g23#165]
The files:
- `backend_services/users_service/api/app/controllers/users_controller.py`
- `backend_services/api_gateway/app/utils/api_gateway_util.py`
- `backend_services/users_service/api/app/utils/users_util.py`

has some missing type hints.

Also, in `backend_services/api_gateway/app/main.py`, this line has some static-analysis error:
```py
        # Send message to microservice
        if service == "matching-service":
            connect_matching_service_websocket(websocket, request)
```

Also, in `backend_services/api_gateway/app/utils/api_gateway_util.py`, these static-analysis errors need to have some type ignores:
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g23/assets/35413456/d8724730-cfd5-44b9-af09-94263586c370)

**Comment by swxk19** [comment]
I'm not too sure what to do about the static analysis errors, since they dont appear on my side
