### ISSUE TITLE
Maintainers don't have matchmaking option

### ISSUE THREAD

**Issue by EvitanRelta** [CS3219-AY2324S1/ay2324s1-course-assessment-g23#199]
idk if it's intentional or not. @afiqzu 

![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g23/assets/35413456/54e10a70-d39c-4366-ac9c-c4711cd360be)

**Comment by afiqzu** [comment]
yeah it is, do you think they maintainers should be allowed to attempt questions and match as well hmm

**Comment by afiqzu** [comment]
Fixed in #205
