### ISSUE TITLE
Errors on profile page doesn't show alert messages

### ISSUE THREAD

**Issue by EvitanRelta** [CS3219-AY2324S1/ay2324s1-course-assessment-g23#200]
On this page, if (for example)u try to change ur name to an already taken username, it won't show anything in the GUI

![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g23/assets/35413456/57a6f3f0-37bd-4192-ab10-f67e26f143fc)

**Comment by afiqzu** [comment]
Fixed

**Comment by EvitanRelta** [comment]
@afiqzu wtf
fast game

**Comment by afiqzu** [comment]
@EvitanRelta ofcc
