### ISSUE TITLE
Unused email field

### ISSUE THREAD

**Issue by swxk19** [CS3219-AY2324S1/ay2324s1-course-assessment-g23#288]
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g23/assets/45385178/c161a8fe-40f8-483e-ad65-1ba5f8732d3b)

Keep or remove? I think it might be something prof could question about. Removing would require a fair amount of refactoring

**Comment by EvitanRelta** [comment]
the email field? i think keep, since its from the assignments

incase we wanna tag the latest commit for assignments, it has to have the email field
