### ISSUE TITLE
Opening question description dialog for the 1st time gives a console error

### ISSUE THREAD

**Issue by EvitanRelta** [CS3219-AY2324S1/ay2324s1-course-assessment-g23#35]
But subsequent opening of the description dialog doesn't seem to log an error

![bug_react](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g23/assets/35413456/5f70e3f9-4fda-4450-bc8c-5e8122326534)

**Comment by afiqzu** [comment]
Fixed in #36
