### ISSUE TITLE
Need to disable lightmode on frontend

### ISSUE THREAD

**Issue by EvitanRelta** [CS3219-AY2324S1/ay2324s1-course-assessment-g23#355]
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g23/assets/35413456/308e748d-7667-4209-b26c-950b41611aa4)

**Comment by EvitanRelta** [comment]
@afiqzu, is this fixed by #362?

**Comment by afiqzu** [comment]
> @afiqzu, is this fixed by #362?

Yep fixed! Will close
