### ISSUE TITLE
Bug in `is_account_owner` in `/database_functions/utils/users_util.py`

### ISSUE THREAD

**Issue by EvitanRelta** [CS3219-AY2324S1/ay2324s1-course-assessment-g23#73]
Here's the current code for `is_account_owner`:
```py
def is_account_owner(user_id, session_id):
    return db.execute_sql_read_fetchone("SELECT user_id FROM sessions WHERE session_id = %s", params=(session_id))[0] == user_id
```
The line:
```
... params=(session_id))[0] == user_id
```

is missing a comma for `=(session_id,)`. Without the comma, the brackets won't form a tuple, and it'll throw an error.

Also, I think the `is_account_owner` might throw an error too when the `db.execute_sql_read_fetchone` call returns an empty array/doesn't return an array. Might need extra checks for that.

**Comment by swxk19** [comment]
Permissions checking has been implemented differently in assignment 4, this function probably won't be used anymore.
