### ISSUE TITLE
Stylise profile details (if needed)

### ISSUE THREAD

**Issue by EvitanRelta** [CS3219-AY2324S1/ay2324s1-course-assessment-g23#80]
For now, I just added a basic display for role + email into the profile popup. 
Idk if @afiqzu u wanna stylise it or smth

![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g23/assets/35413456/9e63af24-e35c-4a83-8a96-2914a70f7502)

**Comment by afiqzu** [comment]
noted 👍

**Comment by EvitanRelta** [comment]
actually, i think it looks ok.

since u didn't change it either, i presuming u think it looks ok too
