### ISSUE TITLE
Backend error when updating user info

### ISSUE THREAD

**Issue by EvitanRelta** [CS3219-AY2324S1/ay2324s1-course-assessment-g23#81]
The backend throws the below error when attempting to update a user's details in these cases:
- update with unchanged user details
- update when changing username/email, with no duplicates

<br>

![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g23/assets/35413456/3a42b0aa-0c0e-4c0b-bb7c-d593a5f8e87c)

**Comment by swxk19** [comment]
@Yaladah I think this should be due to `create_user` not assigning a role when the user creates an account.

**Comment by EvitanRelta** [comment]
@swxk19 my bad. its due to changes to the `get_user` function from my temp fix for #74
