### ISSUE TITLE
Backend doesn't hash new password when updating user's password

### ISSUE THREAD

**Issue by EvitanRelta** [CS3219-AY2324S1/ay2324s1-course-assessment-g23#82]
It doesn't rehash based on this code in `/database_functions/user_functions.py`:

```py
def update_user_info(user_id, username, password, email, role, session_id):
    # ... rest of the code ...
    db.execute_sql_write("""UPDATE users
                        SET username = %s, password = %s, email = %s
                        WHERE user_id = %s""",
                        params=(username, new_password, email, user_id))
    return {'message': 'Successfully updated'}
```

Also, a related bug is #81 which prevents users from even updating their profile details.

**Comment by swxk19** [comment]
It is hashed in the line before
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g23/assets/45385178/cc7e3076-2372-449d-a3aa-2f0f07390759)

**Comment by swxk19** [comment]
I see your code snippet might be from assignment-2, this was fixed in assignment-3. Shall I transfer the fix too? Or can we assume that the assignment demos will be based on the latest version instead?

**Comment by EvitanRelta** [comment]
oop my bad
i think i saw it wrong
