### ISSUE TITLE
Questions can't contain too long of a description 

### ISSUE THREAD

**Issue by EvitanRelta** [CS3219-AY2324S1/ay2324s1-course-assessment-g23#95]
When entering a typical leetcode question like:
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g23/assets/35413456/e53d750e-1cc1-4b9e-915f-69681625df7d)

The backend throws an error saying:
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g23/assets/35413456/8300a8e7-31a2-4a0d-ab73-6b396fad7f7b)

My guess is that the description can't be >255 characters?

**Comment by swxk19** [comment]
Will have to change `VARCHAR(255)` type to `TEXT` type instead.
